# EUREKA CLIENT CONFIGURATION
# In production, you point to your highly-available, replicated Eureka cluster.
eureka.client.service-url.defaultZone=http://eureka-primary:8761/eureka/,http://eureka-secondary:8762/eureka/